### ISSUE TITLE
Removing boxes outside of image

### ISSUE THREAD

**Issue by Fafa87** [rodrigo2019/keras-yolo2#20]
It seems to me that in preprocessing we can get problems if after augmentations some boxes are fully outside of the image:
```         
            bbs = BoundingBoxesOnImage(bbs, shape=image.shape)
            image, bbs = self._aug_pipe(image=image, bounding_boxes=bbs)
            bbs = bbs.remove_out_of_image().clip_out_of_image()

            if len(all_objs) != 0:
                for i in range(len(bbs.bounding_boxes)):
                    all_objs[i]['xmin'] = bbs.bounding_boxes[i].x1
                    all_objs[i]['xmax'] = bbs.bounding_boxes[i].x2
                    all_objs[i]['ymin'] = bbs.bounding_boxes[i].y1
                    all_objs[i]['ymax'] = bbs.bounding_boxes[i].y2
```

If len(bbs) != len(all_objs) then it may be catastrofic as objects can change classes, etc. as we replace coordinates on other box instances.

**Comment by rodrigo2019** [comment]
I agree with you, but I checked the augmentation and  I didn't see any augmentation that create this situation, the augmentation in this repo is not so heavy, I also tried to train with heavir augmentation and I got worst results.
