### ISSUE TITLE
Which dataset were the pretrained models trained on?

### ISSUE THREAD

**Issue by lucpaul** [rodrigo2019/keras-yolo2#23]
Hi,
just looking for a quick clarification. The pretrained models provided here, https://github.com/rodrigo2019/keras_yolo2/releases/tag/pre-trained-weights
Which dataset were they trained on? ImageNet? Coco? How can I find out?

Would really appreciate any info.

Thanks.

**Comment by rodrigo2019** [comment]
Sorry for the late response, but I dont have these informations, I just uploaded the models from experiencior fork
