### ISSUE TITLE
How to change grid dimensions ?

### ISSUE THREAD

**Issue by sinhatushar** [rodrigo2019/keras-yolo2#7]
Original YOLO9000 implementation divides the 416x416 image into 13x13 square grids where each square grid is of size 32x32 (416/13 = 32). I want to divide the image into 208x1 grids such that each grid size is 2x416(rectangular shaped grid).

What all changes do I need to make in the network and at other places in the implementation?
Is changing GRID_H to 208 and  GRID_W to 1 all that I need to do ?

**Comment by rodrigo2019** [comment]
You need change the maxpooling layers inside your backend model

**Comment by sinhatushar** [comment]
![image](https://user-images.githubusercontent.com/32814062/56914606-26508b80-6ad2-11e9-9683-5a549512597c.png)

If I change GRID_H and GRID_W to 208 and 1 respectively as shown in Yolo Step-by-Step.ipynb notebook, won't it work ?
If not, can you please tell me which all maxpoollayers I have to change and to exactly what dimensions if I want to have grid sizes as described above?
P.S. I am a beginner and hence my doubts may look like simple ones but please help me out.

**Comment by rodrigo2019** [comment]
`If I change GRID_H and GRID_W to 208 and 1 respectively as shown in Yolo Step-by-Step.ipynb notebook, won't it work ?`
No.
`If not, can you please tell me which all maxpoollayers I have to change and to exactly what dimensions if I want to have grid sizes as described above?`
Which network as backend are you using? E.g: if you are using Full Yolo as backend, go to the backend model e start to change the kernel size for each maxpooling, you will start to see differents types of grid, you also can exclude the maxpool layers, basically, for each maxpool layer excluded, your grid will be twice bigger

**Comment by sinhatushar** [comment]
`Which network as backend are you using? `
Full Yolo.

Is it easier to change grid dimensions in any other backend configuration ?

I'm sorry I couldn't find  anything named "e start". It appears to me that I will have to change all the maxpool layers in the network. Although I don't understand what will be the change in dimensions of maxpool layers for GRID_H  =  208 and GRID_W = 1. Can you help if it doesn't require a deep dive from you end ?
